export const fullList = [
  { code: "af", name: "Afrikaans" },
  { code: "ar", name: "Arabic (Standard)" },
  { code: "ar-ae", name: "Arabic (U.A.E.)" },
  { code: "ar-bh", name: "Arabic (Bahrain)" },
  { code: "ar-dz", name: "Arabic (Algeria)" },
  { code: "ar-eg", name: "Arabic (Egypt)" },
  { code: "ar-iq", name: "Arabic (Iraq)" },
  { code: "ar-jo", name: "Arabic (Jordan)" },
  { code: "ar-kw", name: "Arabic (Kuwait)" },
  { code: "ar-lb", name: "Arabic (Lebanon)" },
  { code: "ar-ly", name: "Arabic (Libya)" },
  { code: "ar-ma", name: "Arabic (Morocco)" },
  { code: "ar-om", name: "Arabic (Oman)" },
  { code: "ar-qa", name: "Arabic (Qatar)" },
  { code: "ar-sa", name: "Arabic (Saudi Arabia)" },
  { code: "ar-sy", name: "Arabic (Syria)" },
  { code: "ar-tn", name: "Arabic (Tunisia)" },
  { code: "ar-ye", name: "Arabic (Yemen)" },
  { code: "arg", name: "Aragonese" },
  { code: "as", name: "Assamese" },
  { code: "ast", name: "Asturian" },
  { code: "az", name: "Azerbaijani" },
  { code: "be", name: "Belarusian" },
  { code: "bg", name: "Bulgarian" },
  { code: "bn", name: "Bengali" },
  { code: "bs", name: "Bosnian" },
  { code: "br", name: "Breton" },
  { code: "ca", name: "Catalan" },
  { code: "ce", name: "Chechen" },
  { code: "ch", name: "Chamorro" },
  { code: "co", name: "Corsican" },
  { code: "cr", name: "Cree" },
  { code: "cs", name: "Czech" },
  { code: "cv", name: "Chuvash" },
  { code: "cy", name: "Welsh" },
  { code: "da", name: "Danish" },
  { code: "de", name: "German (Standard)" },
  { code: "de-at", name: "German (Austria)" },
  { code: "de-de", name: "German (Germany)" },
  { code: "de-lu", name: "German (Luxembourg)" },
  { code: "de-ch", name: "German (Switzerland)" },
  { code: "de-li", name: "German (Liechtenstein)" },
  { code: "el", name: "Greek" },
  { code: "en", name: "English" },
  { code: "en-au", name: "English (Australia)" },
  { code: "en-bz", name: "English (Belize)" },
  { code: "en-ca", name: "English (Canada)" },
  { code: "en-gb", name: "English (United Kingdom)" },
  { code: "en-ie", name: "English (Ireland)" },
  { code: "en-jm", name: "English (Jamaica)" },
  { code: "en-nz", name: "English (New Zealand)" },
  { code: "en-ph", name: "English (Philippines)" },
  { code: "en-tt", name: "English (Trinidad & Tobago)" },
  { code: "en-us", name: "English (United States)" },
  { code: "en-za", name: "English (South Africa)" },
  { code: "en-zw", name: "English (Zimbabwe)" },
  { code: "eo", name: "Esperanto" },
  { code: "eu", name: "Basque" },
  { code: "es", name: "Spanish" },
  { code: "es-ar", name: "Spanish (Argentina)" },
  { code: "es-bo", name: "Spanish (Bolivia)" },
  { code: "es-cl", name: "Spanish (Chile)" },
  { code: "es-co", name: "Spanish (Colombia)" },
  { code: "es-cr", name: "Spanish (Costa Rica)" },
  { code: "es-do", name: "Spanish (Dominican Republic)" },
  { code: "es-ec", name: "Spanish (Ecuador)" },
  { code: "es-es", name: "Spanish (Spain)" },
  { code: "es-gt", name: "Spanish (Guatemala)" },
  { code: "es-hn", name: "Spanish (Honduras)" },
  { code: "es-mx", name: "Spanish (Mexico)" },
  { code: "es-ni", name: "Spanish (Nicaragua)" },
  { code: "es-pa", name: "Spanish (Panama)" },
  { code: "es-pe", name: "Spanish (Peru)" },
  { code: "es-pr", name: "Spanish (Puerto Rico)" },
  { code: "es-py", name: "Spanish (Paraguay)" },
  { code: "es-sv", name: "Spanish (El Salvador)" },
  { code: "es-uy", name: "Spanish (Uruguay)" },
  { code: "es-ve", name: "Spanish (Venezuela)" },
  { code: "et", name: "Estonian" },
  { code: "fa", name: "Persian" },
  { code: "fa-ir", name: "Persian (Iran)" },
  { code: "fa", name: "Farsi" },
  { code: "fo", name: "Faeroese" },
  { code: "fi", name: "Finnish" },
  { code: "fj", name: "Fijian" },
  { code: "fr", name: "French (Standard)" },
  { code: "fr-be", name: "French (Belgium)" },
  { code: "fr-ca", name: "French (Canada)" },
  { code: "fr-ch", name: "French (Switzerland)" },
  { code: "fr-fr", name: "French (France)" },
  { code: "fr-lu", name: "French (Luxembourg)" },
  { code: "fr-mc", name: "French (Monaco)" },
  { code: "fur", name: "Friulian" },
  { code: "fy", name: "Frisian" },
  { code: "ga", name: "Irish" },
  { code: "gd", name: "Gaelic (Scots)" },
  { code: "gd-ie", name: "Gaelic (Irish)" },
  { code: "gl", name: "Galacian" },
  { code: "gu", name: "Gujurati" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hr", name: "Croatian" },
  { code: "hsb", name: "Upper Sorbian" },
  { code: "ht", name: "Haitian" },
  { code: "hu", name: "Hungarian" },
  { code: "hy", name: "Armenian" },
  { code: "is", name: "Icelandic" },
  { code: "id", name: "Indonesian" },
  { code: "iu", name: "Inuktitut" },
  { code: "it", name: "Italian (Standard)" },
  { code: "it-ch", name: "Italian (Switzerland)" },
  { code: "ja", name: "Japanese" },
  { code: "ji", name: "Yiddish" },
  { code: "ka", name: "Georgian" },
  { code: "kn", name: "Kannada" },
  { code: "kk", name: "Kazakh" },
  { code: "km", name: "Khmer" },
  { code: "ks", name: "Kashmiri" },
  { code: "ky", name: "Kirghiz" },
  { code: "ko", name: "Korean (Standard)" },
  { code: "ko-kp", name: "Korean (North Korea)" },
  { code: "ko-kr", name: "Korean (South Korea)" },
  { code: "la", name: "Latin" },
  { code: "lb", name: "Luxembourgish" },
  { code: "lt", name: "Lithuanian" },
  { code: "lv", name: "Latvian" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "FYRO Macedonian" },
  { code: "ml", name: "Malayalam" },
  { code: "mo", name: "Moldavian" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malay" },
  { code: "mt", name: "Maltese" },
  { code: "my", name: "Burmese" },
  { code: "nb", name: "Norwegian (Bokmal)" },
  { code: "ne", name: "Nepali" },
  { code: "nv", name: "Navajo" },
  { code: "ng", name: "Ndonga" },
  { code: "nl", name: "Dutch (Standard)" },
  { code: "nl-be", name: "Dutch (Belgian)" },
  { code: "nn", name: "Norwegian (Nynorsk)" },
  { code: "no", name: "Norwegian (Standard)" },
  { code: "oc", name: "Occitan" },
  { code: "om", name: "Oriya" },
  { code: "or", name: "Oromo" },
  { code: "pa", name: "Punjabi" },
  { code: "pa-in", name: "Punjabi (India)" },
  { code: "pa-pk", name: "Punjabi (Pakistan)" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "pt-br", name: "Portuguese (Brazil)" },
  { code: "qu", name: "Quechua" },
  { code: "rm", name: "Rhaeto-Romanic" },
  { code: "ro", name: "Romanian" },
  { code: "ro-mo", name: "Romanian (Moldavia)" },
  { code: "ru", name: "Russian" },
  { code: "ru-mo", name: "Russian (Moldavia)" },
  { code: "sa", name: "Sanskrit" },
  { code: "sb", name: "Sorbian" },
  { code: "sc", name: "Sardinian" },
  { code: "sd", name: "Sindhi" },
  { code: "sg", name: "Sango" },
  { code: "si", name: "Singhalese" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "so", name: "Somani" },
  { code: "sq", name: "Albanian" },
  { code: "sr", name: "Serbian" },
  { code: "sv", name: "Swedish" },
  { code: "sv-fi", name: "Swedish (Finland)" },
  { code: "sv-sv", name: "Swedish (Sweden)" },
  { code: "sw", name: "Swahili" },
  { code: "sx", name: "Sutu" },
  { code: "sz", name: "Sami (Lappish)" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "tig", name: "Tigre" },
  { code: "tk", name: "Turkmen" },
  { code: "tlh", name: "Klingon" },
  { code: "tn", name: "Tswana" },
  { code: "tr", name: "Turkish" },
  { code: "ts", name: "Tsonga" },
  { code: "tt", name: "Tatar" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "ve", name: "Venda" },
  { code: "vi", name: "Vietnamese" },
  { code: "vo", name: "Volapük" },
  { code: "wa", name: "Walloon" },
  { code: "xh", name: "Xhosa" },
  { code: "zh", name: "Chinese" },
  { code: "zh-hk", name: "Chinese (Hong Kong)" },
  { code: "zh-cn", name: "Chinese (PRC)" },
  { code: "zh-sg", name: "Chinese (Singapore)" },
  { code: "zh-tw", name: "Chinese (Taiwan)" },
  { code: "zu", name: "Zulu" },
];

export const shortList = fullList
  .filter((lang) => lang.code.length < 4)
  .map((lang) => ({
    code: lang.code,
    name: lang.name.replace(/ \([^)]*\)/, ""), // remove variants in parenthesis
  }));
